### ISSUE TITLE
[Compass Lab]  API development for Lab Model Management

### ISSUE THREAD

**Issue by EdmondFrank** [oss-compass/compass-web-service#43]
```[tasklist]
### Tasks
- [x] Create Lab Model
- [x] Update Lab
- [x] Delete a Lab Model
- [x] Create a Lab model version
- [x] Update a Lab model version
- [x] Delete a Lab model version
```
